jashkenas/backbone

index.html

In the definition for the 'Error' event, the singular nouns 'request' and 'server' require articles. I've also removed the word 'remote' from 'remote server' as the definitions for the 'Request' and 'Sync' events only refer to 'the server'.

Add missing articles ('a', 'the')

---

test/router.js

Since `%20` is decoded by `decodeURI` as well as `decodeURIComponent`, this test was rendered ineffective. Using an escape only decoded by `decodeURIComponent` fixes things up.

Ensure a search test fails when appropriate.

---

backbone.js
test/events.js

Calling `listenToOnce('x y', …)` should be functionally equivalent to `listenToOnce('x', …); listenToOnce('y', …)`.
I realize this isn't the most elegant fix, but it works correctly. The difference in argument order for `listenToOnce` makes it hard to implement `eventApi` for both. I'll look into simplifying though.

Fix #3448. Ensure listenToOnce splits event names.

---

backbone.js
test/events.js

This mirrors the test directly above, ensuring `#once` without a callback noops.

Ensure listenToOnce without a callback noops

---

backbone.js
test/collection.js
test/model.js

Fixes https://github.com/jashkenas/backbone/issues/3283. The only niggle is `Model#destroy` when `isNew`, since it doesn't go through the usual ajax process.

Call the success callback with context

---

backbone.js
test/collection.js
test/events.js

Fixes https://github.com/jashkenas/backbone/issues/3453, and competes with https://github.com/jashkenas/backbone/pull/3049.
I think this aligns more closely with what's currently implemented. :smile:
It also implements `listenApi`, which is `eventsApi` translated to the `listenTo` / `stopListening` method signatures.

Fix listenTo memory leak

---

backbone.js
index.html

Modified the docs for Model.fetch to describe what happens to attributes set on 
the model but not sent by the server. This should address BUG #3477
Before:
Fetch the model from the server. If the server's representation of the
model differs from its current attributes, they will be overridden,
triggering a `"change"` event.
After:
Fetch the model from the server. If the models differ the two are merged. 
Conflicting attributes are overridden by the server's model, triggering a 
`"change"` event.

Fix #3477. Clarify Model.fetch docs

---

backbone.js
test/model.js

This is a really simple change that will allow users to customise the cid prefix to prevent clashes with backend model ids and resolve issues like https://github.com/jashkenas/backbone/pull/3356 and https://github.com/jashkenas/backbone/issues/2920.
I know that this is an edge case but given the small amount of code change required I hope it won't be a problem.

Customise model cid prefix

---

backbone.js
test/events.js

https://github.com/jashkenas/backbone/issues/3460#issuecomment-74762412
Backbone still supports triggering with an object, but the args passed to `#trigger` will not be prepended with the object's value.

Remvoe trigger with object's value prepending

---

backbone.js
test/router.js

This is another take on https://github.com/jashkenas/backbone/issues/2656 to allow an optional trailing `/` for root. Instead of normalizing the root to always include the trailing and the baggage that comes with it (all the `slice`s and having to normalize `location.pathname` to include it), it instead only adds the slash when necessary.
I've kept the following:
```javascript
Backbone.history.start({ root: '/root' });
Backbone.history.navigate('?a=b');
console.log(location.href); `.../root?a=b`
```
But it does not apply when a mandatory trailing slash is added:
```javascript
Backbone.history.start({ root: '/root/' });
Backbone.history.navigate('?a=b');
console.log(location.href); `.../root/?a=b`
```

History's root

---

.travis.yml
karma.conf-sauce.js

[![Sauce Test Status](https://saucelabs.com/browser-matrix/backbonejs.svg)](https://saucelabs.com/u/backbonejs)
Work in progress. Same issues as https://github.com/jashkenas/underscore/pull/2059 + the token isn't currently encrypted. I'll regenerate and encrypted it when travis stops being silly
**DO NOT MERGE WITHOUT GREEN LIGHTS**

Set up sauce test runner

---

examples/todos/index.html
examples/todos/todos.css
examples/todos/todos.js

* Added missing label for "What needs to be done?" text input.
* Added `href` attributes to all `<a>` tags to make them able to be focused with a keyboard.
* Replaced "double click to edit" (which can't be accessed with a keyboard [or from a touch device, for that matter]) with an edit button.
* Associated the TODO item labels with their check boxes.
* Always show the delete button. Showing it only when the parent `<li>` has mouse hover doesn't work with a keyboard (or from a touch device, for that matter).
* Apply the existing `:hover` styles to `:focus` as well. In general you always want to apply styles to both.
* Added the WAI-ARIA `role="button"` attribute to the buttons that are (probably incorrectly) marked up as `<a>` tags. They should really be marked up using `<button>`, but in …

Fix a bunch of accessibility issues.

---

backbone.js

http://jsperf.com/trigger-with-for-loop-vs-slice
One of the optimizations I've found in the linked-list events branch is using a for-loop to grab the trigger arguments. Perf testing `#trigger` on that branch (with slice) against master doesn't tell the whole truth, since this slice call _is_ the performance bottleneck. My linked-list trigger should be roughly ~8% slower than a simple array, but it's a dead heat as long as slice is in there.

Use for-loop, instead of slice

---

backbone.js

Not sure how the maintainers will feel about this . The greatest benefit will clearly be for smaller collections/models.
You can do away with the code to support for length 2 and 4 if you'd rather (`_.filter(_.keys(_), function(name) {return _[name].length === 2})`)
**JSPerf** http://jsperf.com/backbone-underscore-funcs

Optimize underscore proxy methods

---

backbone.js
test/router.js

Fixes #3426.
By using `decodeURI` to decode unicode escapes, `%25` is also decoded. When included in a url parameter, this creates an invalid escape sequence and causes `decodeURIComponent` to throw.
*Sidebar: Should invalid sequences cause the router to throw in the first place? What else can it do?*
Double escape `%25` as `%2525` before using `decodeURI`.
Maybe? I'm pretty happy with the outcome though. I like that we can continue to remove escapes if we come across more problems of this nature. Further, adding it as `History#decodeFragment` means users can customize it to patch things easily when needed.
I'm going to do a bit more research and try to figure out why the browser escapes unicode in the first place. It effectively prevents us from knowing what was escaped by the user and …

Decode unicode escapes without decoding `%25`.

---

test/router.js

This fixes the test in phantomjs by setting the pathname to what it would be anyway in a browser.

Set the pathname explicitly for phantomjs.

---

test/index.html

`setup/dom-setup.js` depends on jQuery so it must be included after.

Sync test scripts with karma config.

---

backbone.js

Fix for issue #3470. Ensures that parse is not called when save is passed the option {parse:false} is set.

Fix for issue #3470

---

.travis.yml
karma.conf-sauce.js

This should make travis builds quite a bit faster - this makes use of our 10 concurrent sessions (we had 3 before) and the new `sudo: false` travis option that makes it faster to spin up builds. Builds complete 1-3 minutes faster and boot much faster.
Also adds Safari 8 to the matrix. TODO fix the bug on karma that makes this necessary :/
-----------------
Also if anyone has an extra VPS they want to donate, it'd be nice to set up testing of pull requests for underscore and backbone (https://github.com/jashkenas/underscore/issues/2085). Send me an email or message me on IRC

Update travis configuration

---

backbone.js

Addresses issues from #3421.
* If your app uses jQuery with AMD or global, or you set `Backbone.$` directly, nothing changes.
* If your app uses jQuery with commonjs, you must specify the dependency in your own app (unchanged). However, we now automatically register `Backbone.$` for you so you can remove the setup line from your code.
* If your app doesn't use jQuery and you're using a commonjs loader like webpack or browserify, you must [tell your build tool to exclude or ignore jQuery](https://github.com/jashkenas/backbone/issues/2997#issuecomment-67675558).
* If your app uses a jQuery mock (like Zepto) with commonjs, you need to aliasify (or use ContextReplacementPlugin if Webpack), or set `Backbone.$` directly.

Wrap commonjs jQuery require in a try-catch

---

index.html

The old documentation makes it look `Backbone.history.start()` starts listening for new hash changes and you have to call `Backbone.history.start({pushState: true})` to route the current URL too. This does not match the behavior in the code.
I removed the `,` from the Backbone.Router documentation to clarify this.

Update documentation for Backbone.Router

---

index.html

The current wording makes it easy to confuse that the model's `changed` property refers to the last time that instance's `set` was called, not any time `set` was called for any model.
Fixes #3235

clarify docs around Model#changed and Model#hasChanged

---

backbone.js
test/router.js

It's hard to believe this has gone unreported for so long, but here it is! Currently, a route like 'test' will match the url `/test`, regardless of the root, and the url `/xxxx/test`, as long as the root is four characters long. This is obviously incorrect as routes should only be executed when the root matches.
There may be further implications from matching the root, but this is certainly more correct than what exists currently.
Thanks to @pfiller for catching it! :heart:

If the root doesn't match, no routes can match.

---

backbone.js

The parent's constructor is 'Function', which is the constructor that created parent. 
The comments refer to the parent constructor function, not it's constructor function (that is, the constructor that created it).

Clarify reference to the parent constructor.

---

backbone.js
test/model.js

Since the `success` callback is called async when `model` isn't new, we should always call `success` async.
Let's not [unleash Zalgo](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony).

Always call success async

---

backbone.js
test/events.js

Based off code from https://github.com/jashkenas/backbone/pull/3476
These are the last changes (hopefully!) from the [eventsApi refactor](https://github.com/jashkenas/backbone/pull/3455).

Refine eventsApi

---

backbone.js
test/collection.js

Events `add` and `remove` are a great way to keep a view in sync with collection. A view can observe when collection's content changes and re-render itself. A model can be added only in the client or loaded from the server and this is transparent to the view.
However, `add` and `remove` are triggered for every single model added/removed, which results in render being called multiple times. This causes performance issues, as rendering can be a heavy operation.
I'm not the first one to encounter this problem:
* http://backbonefu.com/2013/08/handling-multiple-collection-add-models-in-a-batch/
* http://blog.pamelafox.org/2013/06/improving-backbone-app-performance.html
My suggestion is to add a new event `set` that is triggered every time models are added or removed, but just once during one …

Add `set` event triggered once when collection models are added or removed

---

backbone.js

Declares variables when they're needed, instead of all at the top.

Model#set style

---

backbone.js

- Makes it apparent what code needs temporarily `wait`ed attributes
- Uses extend to default `parse` option
- Removes an unneeded object check (just checking for false-y does it)
- Prevents mutating passed in `attrs`
- Declares variables when they are needed, instead of all at the top
(That's the last of the `Model` style updates, I promise. :wink:)

Model#save style

---

backbone.js
test/events.js

When using event maps, it's a little nicer to specify the `context` parameter as the second argument. This keeps backwards compatibility with 1.1.2, though the feature wasn't documented.
```javascript
obj.on({
a: method,
b: other
}, context);
```
When you explicitly pass a `context`, we don't override.
```javascript
obj.on({
a: function() { ok(this === context); },
}, otherContext, context);
```

Juggle context param with event maps

---

backbone.js

Move `addUnderscoreMethods` out of `Backbone.Events` block, adjust comment now that array methods is only 1 method.

Code reorg

---

backbone.js

Some of our tests were failing in Marionette due to jsDom not returning the `document` on `document.open()`. Also it seems that jsDom does not attach the `frameElement` property to `iframe.contentWindow`. I imagine other using jsDom may see similar issues.
Some small changes here, all tests still pass.

Fix opening and closing iframe document in jsdom

---

test/router.js

It was a false positive. Our “location” parsing uses an A tag, which doesn’t always work the way the real location parsing does.

Fix failing IE6 test

---

backbone.js
test/collection.js

Fixes #3636, #2824.
Reverts #1407, so **breaking change**.
Why? To mirror `Model`. `Model#set` doesn’t parse for you, only instantiation, `#fetch`, and `#save` parse.
- We do it on instantiation because we have to have an instance to call `#parse` (you can't do it before hand because you don't have an instance)
- We do it on `#fetch` and `#save` because they return data from the server (the reason we have a `#parse`!)
If you need to parse your `Collection`'s data before `#set`, `#reset`, or `#add`, do it beforehand (you already have an instance):
- `collection.set(collection.parse(models));`
- `collection.reset(collection.parse(models));`
- `collection.add(collection.parse(models));`
Or, you can parse on instantiation if you don't have an instance, just like `Model`:
- `new …

Collection parse

---

backbone.js
test/collection.js

Fixes #3636, but in a backwards compatible way.
Reverts #3644, so that it can be added to v2 release.

Collection#add shouldn't parse a model instance

---

backbone.js
test/collection.js

This is the revert of #3659 (which reverted #3644). So, really, it's just #3644 (which reverted #1407... reverts! :stuck_out_tongue:).
Why? To mirror `Model`. `Model#set` doesn’t parse for you, only instantiation, `#fetch`, and `#save` parse.
- We do it on instantiation because we have to have an instance to call `#parse` (you can't do it before hand because you don't have an instance)
- We do it on `#fetch` and `#save` because they return data from the server (the reason we have a `#parse`!)
If you need to parse your `Collection`'s data before `#set`, `#reset`, or `#add`, do it beforehand (you already have an instance):
- `collection.set(collection.parse(models));`
- `collection.reset(collection.parse(models));`
- `collection.add(collection.parse(models));`
Or, you can parse on …

v2: Collection#parse

---

backbone.js
test/collection.js

As underscore provides it, a Backbone.Collection functional helper should be able to be called with a model-attributes-style predicate (in addition to function-style).
Example:
```js
this.collection.reject({user: 'guybrush'});
```
Methods concerned: find, detect, filter, select, reject, every, all, any, some, partition.
Compatible with underscore#1.7.0.

Collection methods with model-attributes-style predicates

---

backbone.js

Since `#models` is filled with only model instances, there's no need to check if model isn't `null`.
re: #3667.

modelProperty doesn't need to check for null

---

backbone.js
test/events.js

Edge case, but `obj.on({'a b c': increment})` should work the same as `obj.on('a b c', increment)`.

Event maps should support multiple event syntax

---

test/collection.js

Wrapping test object keys as string to avoid IE7/IE8 error (reserved identifiers).
Tests were added with #3667 : https://travis-ci.org/jashkenas/backbone/builds/66548299.

Fix test for IE7/IE8 build

---

index.html

Predefining the **events** hash in a Backbone View is pretty common, and it's not super obvious that **delegateEvents** is where one should look for information about the **events** hash itself.
For instance, Backbone calls delegateEvents before it runs the View's initialize method. If the user explicitly defines the **events** hash in the View itself, then there is a chance that the user never has to explicitly call delegateEvents at all. 
I think it stands to reason that the **events** hash property get its own section in the docs.
**1. Edit:** Cleaned up whitespace, wrapped long lines, corrected wording.
**2. Edit:** Used better wording suggested by @akre54.
**3. Edit:** Refactor example View code as suggested by @akre54 and @megawac.

Add docs for View#events

---

index.html

The most recent style clean up caused the example code block to run off into the margins.
**This:**
**Becomes this:**

Refactor example code in View#events docs

---

package.json
test/setup/dom-setup.js
test/view.js

Karma QUnit v0.1.5 now removes and reinserts the `#qunit-fixture` element before every test.
Ping https://github.com/karma-runner/karma-qunit/issues/28 and https://github.com/jashkenas/backbone/pull/3742.

Setup DOM for every view test

---

backbone.js

Since lodash v4 [will be removing](https://github.com/underdash/underdash/issues/4#issuecomment-118974230) the `context` param of methods Backbone can avoid a minor compat issue by deferring to `_.bind` for both cases in `sort`.

Use `_.bind` instead of `context` param of `_.sortBy`.

---

backbone.js

Closes #3672 (kind of, we still can't deprecate `Collection#include` until we officially bump our underscore dependency to 1.8).

Add Collection#includes for underscore v1.8

---

test/collection.js
test/vendor/underscore.js

Adjusts tests to follow up #3676.

Use `some`, `includes`, `map` in tests instead of `any`, `include`, `pluck`.

---

index.html

For https://github.com/jashkenas/backbone/issues/3720
While this is short update, other than the underdash stuff, both additions are featurey and much less bugfixy so I'd suggest a minor point bump.
Style references:
- Listing multiple methods: https://github.com/jashkenas/backbone/blob/1.2.1/index.html#L4445
- Similar backbone event entry https://github.com/jashkenas/backbone/blob/1.2.1/index.html#L4539
Ponderings:
- Should the model-attribute-style predicate functionality be documented better elsewhere and just referenced here?
- The fairly generic underdash log entry could be removed, though it seems as if that is predominately why this release is shipping now.  If it stays, should we link out to Underdash's github?
Todo:

Draft change log for Backbone 1.2.2

---

backbone.js
test/collection.js

This is a backwards compatible version of #3648.
- Declares variables where they are needed (and removes duplicate `var i` declarations)
- Exits early when `models` is nullish
- Makes the "merge" and "add" loop easier to follow
- Makes inserting models with `at` an order of magnitude faster
- [Base case (`#unshift`)](http://jsperf.com/insert-array-into-another-array/14)
- [Base case (`#push`)](http://jsperf.com/insert-array-into-another-array/15)
- ["Normal" collection size](http://jsperf.com/insert-array-into-another-array/16)
- [Large collection](http://jsperf.com/insert-array-into-another-array/17)
- [Big fetch](http://jsperf.com/insert-array-into-another-array/18)
Depending on how much performance is an issue, we can use an even faster splice algorithm (also included in the jsperfs), …

Collection#set style (Backwards Compatible)

---

backbone.js
test/collection.js

@jridgewell 
Fixes an issue noticed when running Marionette tests against 1.2.2. Adding a model at index 5 to a collection with a length of 3 throws an error. Previously this would add to the end of the collection.

fix error when adding model to collection at an out of bounds index

---

backbone.js
test/collection.js

Fixes #3693.
This leaves open the question of whether events triggered on the model
during a ‘remove’ listener should also trigger on the collection. Just
something to revisit for V2.
```js
col.on('other', (model) => {
// Should this be triggered?
});
col.on('remove', (model) => {
// If the model is really "removed" (we can't `#get` it anymore)
// by the time this listener is called, then I'd argue that this
// shouldn't trigger the 'other' event on the collection...
model.trigger('other');
});
```

Fix _removeModels regression

---

test/collection.js
test/events.js
test/model.js
test/noconflict.js
test/router.js
test/sync.js
test/view.js

Fixes #3813.
I had to manually migrate `test/router.js` because my migrator apparently can't handle non-ASCII characters. Please do pay special attention to that one.
I don't know CoffeeScript that well, but it looks like the assertions in that library are simply falling back to the Node environment (and therefore its assert module). Thus I assume no modification needs to happen to that file (due to it not actually being QUnit tests). Please let me know if this is incorrect.

Migrated tests to QUnit 2.0 syntax.

---

index.html
test/collection.js

*Updated:*
The documented example shows passing `[]` to instantiate an empty collection
while still supplying an options object. This change makes the preceding
documentation consistent with that example.
I also noticed that we don't have any tests covering the previously recommended
approach of passing `null` (or any falsey value) for models. I've added a test
to ensure we continue to support that usage.

Document using [] for Collections with zero models

---

.travis.yml
karma.conf-sauce.js
package.json

As of 0.13.12 karma supports a concurrency field to limit browsers started in parallel. See karma-runner/karma#1646
Don't merge til green lights
Have to still tinker with the concurrency limit. I think we should be able to set 10
Webkit based browsers will currently pass all tests but give an error. See karma-runner/karma#1101 & karma-runner/karma#1648

Use karma concurrency for initiating parallel sauce tests

---

backbone.js
test/collection.js

All of our currently deoptimized Underscore methods (`pick`, `omit`, `invoke`, `without`, and `difference`) change behavior based on the number of arguments pass to the call. This both adds `reduce` (and friends).
Supersedes (and incorporates) #3810.

Deopt Underscore methods that change on arguments

---

backbone.js

This makes way for `_.invoke` to be renamed `_.mapInvoke` or other in lodash v4 (due out in Jan 2016).

Change `_.invoke` to `_.map`.

---

backbone.js

This PR ensures `attr` is a string when passed to `this.map`. I've had folks rely on the undocumented behavior of letting iteratees slip through if `attr` is not coerced.

Ensure `attr` is a string when passed to `this.map`.

---

package.json

npm automatically sets up $PATH to look in node_modules/.bin

trust npm to set up $PATH

---

.eslintrc
test/collection.js
test/model.js

Constructor functions must start with a capital letter.
Since #3894 has been slow to merge, I'm going to try opening per-commit pull requests which should be easier to review/discuss.

Enable ESLint rule: new-cap

---

.eslintrc
backbone.js

An alternative to #3898. Note that while this allows us to keep our tests in their current state, it brings `backbone.js` slightly farther away from the UMD template (https://github.com/umdjs/umd/blob/master/templates/amdWebGlobal.js)

Add ESLint rule: wrap-iife (inside)

---

.eslintrc
backbone.js
test/.eslintrc
test/collection.js
test/events.js
test/model.js
test/noconflict.js
test/router.js
test/sync.js
test/view.js

In an attempt to batch these changes together, this pull request includes a number of new rules (all taken from Underscore's `.eslintrc`).
Each commit reflects the changes needed for a single rule, so I would recommend reviewing by commit.
@akre54, @megawac c4b27bd May be controversial in the same way that https://github.com/jashkenas/backbone/pull/3893 was.
If we want some but not all of these, I'm happy to go back to submitting them as individual pull requests.

Large batch of ESLint cleanups

---

.eslintrc
backbone.js
test/events.js

This is only enabled as a warning, since in some cases I think it adds clarity. I left the "gratuitous parentheses" when they were clarifying nested ternary operators or clarifying the evaluation order of `&&`s and `||`s.

Add ESLint warning: no-extra-parens

---

.eslintrc

By allowing the single-line exception, we can add this rule with no changes.

Enable ESLint brace-style

---

backbone.js

While looking into adding the "no-nested-ternary" ESLint rule, I realized that this logic could be refactored a bit.
This nested ternary was introduced in pull request #3875 in order to handle falsy returns from `parse()`.
This refactor avoids the nested ternary and also makes the intent clearer by associating the empty array directly with `parse()`'s return.
It also more narrowly handles the falsy case (we never intended to allow you call `set(0)` for example.)
The only down side I can see is that if `parse()` returns falsy, we will unnecessarily slice/clone the empty array we just created.
(@jridgewell)

Avoid nested ternary

---

backbone.js

This is both grammatically correct, and consistent with the language in the rest of the comments.

Update wording to "space-separated" to be consistent

---

.eslintrc

Unlike pull request #3904, this pull request includes the "allowShortCircuit" exception which allows us to keep our code as it is.

Add ESLint rule: no-unused-expressions

---

backbone.js
test/collection.js

Adds a `has` method to the collection prototype. Analogous to Model#[has](https://github.com/jashkenas/backbone/blob/master/backbone.js#L451)

add `has` method to collection

---

index.html

The modelId docs on backbonejs.org were [fixed](https://github.com/jashkenas/backbone/commit/8011b5c75b60a88a61abe0a3779b70b1b2bbeda9) (though not yet on backbonejs.org). This fixes an oversight which results in `dvdundefined` and `vhsundefined` being stored and accessed in the _byId object :) 
Also, breaks the final line up for display reasons

fix modelId example

---

backbone.js
test/events.js

Upon upgrading, I found that Events.once was no longer passing context through when using object notation.
```javascript
this.once({closed: this.onClosed, shown: this.onShown}, this);
```
Other event handling forms were still functioning properly:
```javascript
this.on({closed: this.onClosed, shown: this.onShown}, this);
this.once('closed', this.onClosed, this);
this.once('shown', this.onShown, this);
```
I couldn't find a changeset explaining why `undefined` was being passed through instead of the callback object, but doing so drops the context when two arguments were used.

Fixing object notation for Events.once

---

docs/backbone.localStorage.html

Found a spelling mistake -
`deprectated` > `deprecated`

Fixes typo in docs

---

backbone.js
test/model.js

This is definitely an underscore concern, but it's easier to demo in Backbone code.
Fixes #3842.

Avoid Object.prototype collisions with defaults

---

test/view.js

This should fix two of the failures in the test cases.
The other failure seems to be that in IE8 `onhashchange` is added to `window`. I'm not familiar enough with `attachEvent` (does it automatically create a global `onhashchange`?), but it seems that us calling `Backbone.history.stop()` isn't enough to remove the global. Anyone with IE experience care to shed some light?
There were a few other failures in https://travis-ci.org/jashkenas/backbone/builds/119075098 around default model attributes in IE8 too.

Fix failing global tests

---

index.html

I've used this method today and I have to test what it will return if no model matches, so I decided to make this pull request to make things clear in docs.

Explicitly specified return value for findWhere if no model matches.

---

backbone.js
test/router.js

Fixed updating URL with uri-decoded value

---

backbone.js
test/collection.js
test/model.js
test/router.js
test/view.js

This is my attempt to allow for better support for ES6 classes through a new method, localProps.
`localProps` allows you to define a function (or an object), that is evaluated in the constructor for Models/Collections/Views/Routers, with the result being mixed in to each local object.
As a happy side effect this allows a declarative format for instance properties on an object (instead of using `this.foo = 'bar'` statements in the constructor).
This allows us to write something like 
```
class DocumentRow extends Backbone.View {
localProps() {
return {
tagName:  "li",
className: "document-row",
events: {
"click .icon":          "open",
"click .button.edit":   "openEditDialog",
"click .button.delete": "destroy"
}
};
}
initialize() {
this.listenTo(this.model, "change", this.render);
} …
```

Add a preinitialize method to allow for true instance properties and ES6 classes

---

index.html

The docs should state explicitly that `model.id` should not be manipulated directly. (See #4004)

Clarification on the use of model.id

---

.eslintrc
package.json

Of note:
* `no-empty-label` was replaced with `no-labels`. If we want to loosen behavior to allow sensible labels, we can make that change, but there were no errors on tightening.
* `space-after-keywords` and `space-return-throw-case` were consolidated into `keyword-spacing`. To preserve behavior
I also removed an unnecessary/redundant set of array brackets on a rule that had no extra options.

Upgrade ESLint to latest and replace removed rules

---

.gitattributes

When I ran ESLint on my local machine, I got many, many `linebreak-style` errors. This is because my local `git` was checking out the files with Windows-style line endings. Adding this file will ensure files are checked out and committed with Unix-style line endings even on Windows machines, for all contributors.
To be safe, I only applied this to JavaScript files, since those are the only ones that go through linting anyway.
Please let me know if I need to modify the commit summary for changelog purposes (or any other purpose).

Adding .gitattributes to force Unix line feeds

---

backbone.js
test/collection.js

This introduces new methods related to Iterators on Backbone.Collection to mirror those found on Array: `values`, `keys`, `entries`, and `@@iterator`. Each of these methods will return a JavaScript Iterator, which has a `next` method, yielding the models or ids of models contained in the Collection.
The CollectionIterator is careful to use the `at()` and `modelId()` methods on the host collection rather than direct access to the `models` property, which should ensure it is resilient to creative subclassing of Backbone.Collection and future feature addition.
CollectionIterator's `next` method follows the same [algorithm defined by ES6 for ArrayIterator's `next`](http://www.ecma-international.org/ecma-262/6.0/#sec-%arrayiteratorprototype%.next).
The …

Implements the JavaScript Iterable protocol.

---

docs/search.js
index.html

This is a direct port of @captbaritone's changes in jashkenas/underscore#2514, as suggested by @jashkenas. It allows you to quickly filter through the documentation by the listings in sidebar, and jump to the first match by pressing Enter. The functionality can be tried out here: https://rawgit.com/msrose/backbone/docs-search/index.html.
I've made every list item in the sidebar searchable based on the inner text of the contained `<a>` tag. There is a greater variety of items listed in the backbone docs compared to the underscore ones, but I think it still makes sense to have everything searchable based on the current implementation of the filtering.
The code includes includes the ability to filter by "alias" (i.e an alternate name for a function), which is useful in underscore but has no …

Add filtering to documentation

---

karma.conf-sauce.js

In the future we can talk about removing some of the kludges for oldIE. For now we just won't be testing for <= IE8, with the goal of eventually refactoring some of the older hacks out.

Stop testing IE8 in sauce

---

index.html

This fixes #4109 by indicating that any set on a model, which causes a
change event will results in the change event being bubbled up to the
collection.

Clarifies that changes cause Collection update event

---

backbone.js
test/events.js

Fixes https://github.com/jashkenas/backbone/issues/3611.
This uses a private `listening` var to share state between a Backbone
"listener" and "listenee", instead of using a private `internalOn()` to
share state. This allows `#listenTo` to use the public `#on` method and
keeps interop between Backbone and any other event library.
http://jsperf.com/internal-listening-public-on

Use the public `on` method when listening

---

backbone.js
test/collection.js
test/model.js

Adds Collection & Model mixins for adding custom implementations of iterator/check methods to base collection and model. The main motivation of this is to add some `lodash` methods that were missing on the prototype.
Ideally one could do
``` js
Backbone.Collection.mixin({
sum: lodash.sum,
take: lodash.take
});
```
However, I don't have a good idea of how to support iteratees, so things like `collection.sum('value')`
Thoughts? /cc @akre54 @jridgewell

Collection & Model Mixin

---

index.html

Given that route wildcards have names, it is easy to expect they might be passed to the action function as key/value pairs.
Additionally, the definition of an "action" is quite vague, and could easily be confused with an event or some other construct. I've attempted a minor improvement here.

Clarifying improvements to router documentation

---

index.html

- Include a description of the events triggered in Model#isValid.
- Separate the explanation of the validation in the methods `save` and `set` from the `validate` method itself.
- Add `options` parameter to Model#isValid to resemble its implementation.

Clarify documentation of Model#isValid and Model#validate

---

backbone.js

this would technically close #4145 since it's the only thing I found that would break compat with upcoming lodash 5 changes, unless @jdalton has anything to say about here or through https://github.com/lodash/lodash/wiki/Roadmap

`_.bind` to `Function.prototype.bind`

---

index.html

- Mention that Options can be provided in section "Collection-model" of documentation.
- Mention that Options can be provided in section "Collection-add" of documentation.
- Mention that Options can be provided in section "Collection-create" of documentation.

Mention use of Options on Collection#model handling of Model instantiations

---

backbone.js
test/collection.js

For Issue: https://github.com/jashkenas/backbone/issues/3965
- `modelId()` now takes the idAttribute of the model in question as the second argument
- `modelId()` will use the passed `idAttribute` before falling back to `Collection.prototype.model.idAttribute` and then `'id'`
- Retains backwards compatibility
- Update tests to show default `modelId()` fallbacks
- Update tests to show default polymorphic collection behavior
Right now `modelId(attrs)` is only passed a plain-object representation of the model's attributes. This makes it difficult for application developers to create n-degree polymorphic Collection subclasses.
Contrived Example:
``` javascript
// A collection of mixed entity types that maintains sort order based 
// on their joinDate property
var Entities = …
```

Update `modelId()` to Allow Polymorphic Collections with Different, Unknown, Model.idAttributes

---

index.html

The event listener was missing a closing parenthesis in the preinitialize code sample for Collections. This is reference to issue #4237

Added missing parenthesis in the Collection preinitialize code example

---

backbone.js
test/collection.js

Simple check that `this.model` is constructor. We could have more complicated check, but looks like it doesn't required.
Fixes #4233

Add check for `this.model.prototype`

---

backbone.js
index.html
test/collection.js

Fixes #3882
Fixes #4159
Backbone does a bit of extra work to determine when to update `_byId` on every model change event because `change:id` will not work if `idAttribute` has changed.  This causes issues as the `change` event happens after every `change:` event which means during a change the `_byId` hasn't updated.  Rather than adding complexity to collection the solution is to have the model notify with the id changes.
If adding a public event isn't desired, for an internal solution the model is aware of it's collection and could modify model.collection._byId directly within the set.
Either of these solutions seem preferrable to handling `change:[idAttribute]`
Replaces the need for:
https://github.com/jashkenas/backbone/pull/4227/files#diff-c773bb9be277f0f3f2baa308b6e0f3a486790fe99fea8 …

Add model changeId event

---

.eslintrc
.github/workflows/tests.yml
backbone.js
karma.conf-sauce.js
package-lock.json
package.json
test/collection.js
test/events.js
test/router.js
test/view.js

This is a continuation of @ogonkov's work at #4251, which I'm personally pushing directly to the main  repo in order to rule out any effects from permissions. I also wanted to try a couple of things. If I end up merging this branch, #4251 will automatically be recognized as merged as well.

Fix test workflow, bis

---

package-lock.json
package.json
test/model.coffee

CoffeeScript 2 came out in 2017. This PR updates Backbone’s CoffeeScript dependency to version 2, and updates the related test per https://coffeescript.org/#breaking-changes-super-extends.

CoffeeScript 2

---

examples/backbone.localStorage.js

There is a small typo in examples/backbone.localStorage.js.
Should read `deprecated` rather than `deprectated`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, deprectated -> deprecated

---

backbone.js

This proposal replaces #4088 by @unclechu. I squashed their commits and then changed the comment again in a commit of my own. In this way, @unclechu is still credited for their effort to document the code, although their PR will be marked as rejected.
In my opinion, the line in question was misguided (see also #4266). It has no advantage over a simple call to `_.defaults`, except that it allows you to set attribute keys that collide with `Object.prototype` properties. I consider that a footgun rather than a feature.
Reviews welcome.

Comment about combined defaults and extend

---

backbone.js
index.html
test/router.js

Fixes #3391 - Allow developers to control whether a trailing-slash should be included or not.

#3391 - Match trailing slash on root to how root was configured.

---

backbone.js
test/collection.js
test/model.js

This fixes #4262.
The bug arose because the transaction with the backend is mediated through `model.save` and the `'error'` event is initially triggered by the model. Normally, the collection will forward all events from the model, but with `wait: true`, the model is not yet added to the collection when the event triggers, so the collection is not listening, either. I addressed this by special-casing the `'error'` event in this particular scenario.
I determined that a similar fix is not required for the `'sync'` event on successful `create`. In that case, the model is still added to the collection before the event triggers.
I foresee two possible criticisms on the solution:
1. One could argue that a similar fix is still needed for the `'request'` event. However, since the timing of this …

Trigger error from failing Collection.create with wait:true

---

index.html

Closes #3496. I moved some of the documentation for `Collection.add` to `Collection.set` and added documentation on sorting, so that the latter now gives a complete overview of the options, return value and events. I added a reference from `Collection.add` to `Collection.set` and from `Collection.{push,unshift}` to `Collection.add`, clarifying how these methods differ from each other.
The updated documentation can be previewed here: https://cdn.statically.io/gh/jgonggrijp/backbone/document-add-push-unshift/index.html.

Clarify relationships between set, add push and unshift

---

index.html

Closes #4226. The updated documentation can be previewed at https://cdn.statically.io/gh/jgonggrijp/backbone/document-cidPrefix-conflict/index.html.

Document Model.cidPrefix

---

.editorconfig

I've been keeping an untracked `.editorconfig` for the past couple of days, because I usually use 4-space indentation while Backbone uses 2-space indentation.
I plan to modularize Backbone and grasp the opportunity to switch to 4-space indentation, since it is a major code disruption anyway. This will be easier to manage between different branches if I commit the `.editorconfig`.
If somebody thinks I should **not** change the indentation, now is the time to tell me! (Don't worry, I will keep different types of changes in separate commits so they are easier to trace.)
There is currently a subsection for `package.json` because that will have to stick to 2-space indentation. I don't mind removing the special case for the time being. Other comments on details are also welcome.

Add a .editorconfig; prepare for switching to 4-space indentation

---

README.md
SECURITY.md

I literally copied the `SECURITY.md` from Underscore and `s/underscore/backbone`. I expect this to be uncontroversial, partly because @jashkenas reviewed and agreed to the Underscore policy at the time.

Security policy

---

index.html

Please see #4205 for a rationale of this change. My thoughts that led to this PR are in the bottom comment.
I have asked myself whether this should be documented at all, given that it is a rather obscure corner case (user sets the model id to a fixed value in the defaults and also adds instances of the model to a collection). However, the fact that #4205 was reported proves that users may encounter the situation.
The edit can be previewed as web page over here: https://cdn.statically.io/gh/jgonggrijp/backbone/document-defaults-idAttribute/index.html#Model-defaults.

Add warning to documentation about setting the model id in the defaults

---

backbone.js
index.html
test/router.js

This is a new feature that I factored out of an application I built at Utrecht University. It makes it possible to display a generic "404 not found" view whenever the URL changes but does not match any route known to `Backbone.history`. In the application, I hacked the feature in by overriding `Backbone.history.loadUrl`, which is an undocumented method. With this feature added to Backbone itself, that hack would no longer be necessary.
It was already possible to inspect the return value of `Backbone.history.start()` and display a 404 view if that value was `false`. However, there was no way to detect a non-matching URL that occurred after a `hashchange` or `pushstate` event, for example due to a coding error or a creative user hacking faulty URLs into the page. The `notfound` event …

History notfound event

---

.github/ISSUE_TEMPLATE/Bugs.yml
.github/ISSUE_TEMPLATE/Documentation.yml
.github/ISSUE_TEMPLATE/Features.yml
.github/ISSUE_TEMPLATE/config.yml
backbone.js
debug-info.js
index.html
karma.conf-sauce.js
karma.conf.js
modules/.eslintrc
modules/debug-info.js
modules/package.json
package-lock.json
package.json
test/debuginfo.js
test/index.html

I decided to try my hand at GitHub's issue template functionality. The changes can be previewed [at my fork](https://github.com/jgonggrijp/backbone/issues/new/choose), where I temporarily enabled issues. This is probably a better way to review this PR than by reading the YAML files. The top three categories have forms that you can view by clicking "get started".
I had two main goals:
1. Steer people away from reporting security vulnerabilities through public issue tickets. Those should be communicated privately to me and Jeremy instead.
2. Guide inexperienced users to document their issues as clearly as possible.
For expert users, there is still the option to skip the forms and create a blank issue.
I may have gone a bit overboard with the forms. I'm open to all suggestions.

Issue templates

---

test/vendor/underscore.js

1.Use allowed instead of whitelisted.
2.Use disallowed instead of blacklisted.

Use allowed instead of whitelisted; Use disallowed instead of blacklisted;
