jashkenas/backbone

backbone.js, test/collection.js
Closes #3353.
I noticed this one still sitting around so I added a patch with a test.
=> Collection#set - options.at accepts a string.

test/events.js
To be clear, I think the trigger with object behavior is silly. But I needed tests to ensure that my [`eventsApi` refactor](https://github.com/jridgewell/backbone/tree/eventsApi-refactor) kept the current functionality.
Re: https://github.com/jashkenas/backbone/issues/3460
=> Test trigger arguments behavior

backbone.js, docs/backbone.html
Updated the copyright from `2014` to be `2015`.
=> Fixed copyright range to be updated to 2015

backbone.js, test/router.js
Reverts jashkenas/backbone#3443
=> Revert "History's root"

backbone.js, test/collection.js, test/model.js
Better version of #3484. Fixes #3478.
=> Include updated options in sync callbacks

index.html
=> Add documentation about collection.remove `models` arg.

backbone.js
Extracted from https://github.com/jashkenas/backbone/pull/3443#discussion-diff-22830716
=> Use _use* properties to determine "wants" and "has"

.travis.yml, karma.conf-sauce.js
IE6 is still creating issues. Not sure what was wrong with these 2 browsers earlier
=> Test IE7 & IE8

examples/todos/index.html, examples/todos/todos.css, examples/todos/todos.js
Reverts jashkenas/backbone#3338
=> Revert "Fix a bunch of accessibility issues."

index.html
=> Fix wording in validate docs

backbone.js
[It's not actually effective](http://mrale.ph/blog/2014/12/24/array-length-caching.html) and it makes the code uglier. 
JSPerf is down at the moment but I seem to remember the benefits in older browsers not even being that great. @jdalton, what say you?
=> Remove the micro-opt of caching array length

backbone.js, bower.json, package.json, test/model.js, test/vendor/underscore.js
As suggested by @megawac in #3307 allow `Model#matches` to take a predicate function.
=> Matches with predicate

backbone.js
Remove comma from comment. No changes to source code made.
=> Fix grammar in Helpers documentation.

backbone.js
Up for discussion, see https://github.com/jashkenas/underscore/pull/2153 comments
Amendment to 5a6ffcb873ec555bda9d623b411a243da4efc9a7
=> Amend #3566 fix; global detection

index.html
=> Typo @ index.html

backbone.js, test/collection.js
Fixes https://github.com/jashkenas/backbone/issues/3610.
=> Collection#invoke should collect arguments

backbone.js
Also, use the same slash normalizing as Router and History
=> Grab id using #get in Model#url

backbone.js, test/model.js
- Respect `#fetch`'s `parse` option (extends #3508)
- Use extend to default `parse`
=> Model#fetch parse option

backbone.js, test/collection.js
Instead of returning a boolean, just return the removed models (or false if nothing is removed).
=> Return removed models from #_removeModels

index.html
be sure to cherry-pick to gh-pages after merge
=> Document delegateEvents change from #3060

backbone.js, test/router.js
Remove the only `_.bindAll` use.
=> Remove the only `_.bindAll` use.

backbone.js
Replace `_.any` with `_.some`.
=> Replace `_.any` with `_.some`.

backbone.js
On the back of #3631, let's consistently `#get` to grab the `idAttribute`.
=> Update model's id with #get

backbone.js
This is an attempt to unify and clarify Backbone's comments to make it easier to understand some of the tricky parts. Particularly where we have extra optimizations and higher-order functions (underscore methods and Events mainly), it'd be great to make sure it's clear *why* we're doing what we're doing.
I'd also like to detangle `Events` even further. There's a lot going on there that can be hard to follow at first and is very implementation-specific. Some info about the way we're passing around listen ids and callbacks would go a long way, I think.
For instance: @jridgewell should we rename `memo` in `eventsApi` to `events`? I get that it's a reference to `reduce`, but I think the `memo` terminology is confusing, especially since, with the exception of `once`, it always refers to the …
=> Update comments throughout the code

index.html
=> update docs according to issue #3694

index.html
Adjust toc_section's font to "Lucida Grande", "Lucida Sans Unicode", Helvetica, Arial, sans-serif; for better display on Windows.
=> Update index.html: adjust toc_section font for better display on Windows

backbone.js
Add Modernizr style check for 'onhashchange' to avoid issues in IE compat modes for #3730.
=> Add Modernizr style check for 'onhashchange' to avoid issues in IE compat modes.

docs/todos.html
I found a broken link in [the document](http://backbonejs.org/docs/todos.html#section-1), so that fixed it. :)
=> Fixed a broken link.

package.json
[NPM includes LICENSE automatically.](https://docs.npmjs.com/files/package.json#files)
https://github.com/jashkenas/underscore/pull/2264
=> Remove LICENSE from package.json files array.

index.html
=> Document delegate/undelegate

.travis.yml, karma.conf-sauce.js
Add <img src="https://saucelabs.com/images/scoutbar-two/big/microsoftedge.png" title="MS Edge" height=3% width=3%> to karma-sauce runner.
=> Add MS Edge to karma-sauce runner.

README.md
Github issues are the wrong forum for general discussion and questions (see #3734). Let's direct folks to the right venues.
=> Add alternative help channels to README

index.html
http://underscorejs.org/#matches doesn't work and is an alias (that may be deprecated)
=> Remove _.matches proxy ref in docs

index.html
Make documentation a little clearer. Addresses #3688
=> update modelId docs

index.html
A short fix for https://github.com/jashkenas/backbone/issues/3789 - I hope not to take unnecessarily too much space.
=> Docs for Collection#at behavior

backbone.js, test/collection.js
=> Add `findIndex` and `findLastIndex` underscore methods to Collection.

package.json
=> Revert "Remove LICENSE from package.json files array."

backbone.js
=> Fix 1.2.2 Model#id regression

backbone.js, test/collection.js
=> Always return removed array from #_removeModels

backbone.js, test/collection.js
=> Fix _onModelEvent regression

test/model.js
Re: https://github.com/jashkenas/backbone/pull/3833#issuecomment-152842054
=> Test case for model.id

examples/backbone.localStorage.js
=> fixed typo

test/setup/environment.js
=> Enable QUnit.config.noglobals in tests

backbone.js
Simplify `pluck`.
Related to https://github.com/jashkenas/backbone/pull/3864#issuecomment-159164574.
=> Simplify `pluck`

backbone.js, test/collection.js
Restored previous code for this logic.
Added a regression test.
Fixes #3871
=> Fixed Collection#set regression when parse returns falsy value

.eslintrc, backbone.js, test/collection.js, test/events.js, test/model.js, test/router.js, test/sync.js
I would recommend reviewing each commit individually. I'm happy to split this up into multiple pull requests if any of these changes are controversial.
=> Enable ESLint rules: block-scoped-var, dot-notation, eqeqeq

LICENSE, backbone.js
I saw https://github.com/jashkenas/underscore/commit/0e6d1e545451cba9838ad8883384f6872980a8be and figured a similar change was in order over here.
=> Update copyright year

.eslintrc, backbone.js, test/collection.js, test/model.js, test/router.js, test/sync.js, test/view.js
`col` is already defined and referencing a collection
<b>edit</b>: removed all shadowed variable declarations
=> eliminate shadowed variable declarations

test/collection.js
cf https://github.com/jashkenas/backbone/pull/3932
=> add tests solidifying behavior for modelId with polymorphic models

.travis.yml
See https://github.com/npm/npm/issues/11283
=> disable npm's progress bar in travis ci for quicker install

backbone.js, test/collection.js
Fixed a couple bugs, addressed the nits and preformed the rebase for https://github.com/jashkenas/backbone/pull/3711. Should be a quick review /cc @akre54 
Closes #3711; Fixes #3700
=> Pass updated models in the Collection "update" event

test/vendor/qunit.css, test/vendor/qunit.js
I'm getting failures when testing locally that `assert.notOk` isn't a function. :cry:
Testing the boolean return values is probably intended anyways.
=> Use strictEqual in Collection#has Tests

test/collection.js
=> fix failing linting tests

backbone.js
Fixed spacing after return to match the rest of the code
=> Line 1920 - Fix Spacing After Return

index.html
Qualify the behavior of fetch({reset: true}). Link doc on reset event to reset method.
P.S. I know index.html is served from the gh-pages branch, but could not find instruction on where to commit doc and looks like master is ahead of gh-pages. Also not sure whether HTML was being built from anything - doesn't look like it. Couldn't find instruction.
=> Minor update to docs. 

backbone.js, test/events.js
ping #3975
/cc @jridgewell  @elgubenis
=> Fix 1.3.1 regression with once and no context

index.html
Trivial fix on a broken link in the documentation.
related to issue #3990
=> Fixed broken link to MDN array sort

index.html
Hopefully this saves someone else's time 😄
=> Fix changelog referring to wrong code change

.gitattributes
Reverts jashkenas/backbone#4036
=> Revert "Adding .gitattributes to force Unix line feeds"

docs/search.js, index.html
__Note:__ This pull request is to `gh-pages` not `master`.
Cherry-pick @msrose's "Add filtering to documentation" (#4075) pull request onto the `gh-pages` branch.
=> Deploy filtering

index.html
- Loads and saves [data] from the server.
=> Fix description for Model

index.html
@megawac I took a 2nd attempt at this. PTAL.
=> Add Changelog for 1.4.0

.travis.yml
Since the CI was acting up, I figure I might as well as update the node version and hope it works.
=> Update travis ci to use node 6 since it's in LTS

.github/workflows/tests.yml
=> Fix workflows

CONTRIBUTING.md
=> Encourage contributors to document new features in the index.html

LICENSE, backbone.js, index.html, package-lock.json, package.json
I realized there was some unfinished work lying around, which deserved a release.
After an approving review, I will add another commit with the generated files (i.e., docco and the minified code) and then upload the release to NPM.
@stephenkao I saw your response to #4268 and wanted to send you a formal review request, but GitHub's Reviewers form field would not let me do it. I hope a mention works for you.
=> Prepare release 1.6.0
